#!/bin/bash

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${ENV_FILE:-$SCRIPT_DIR/.deploy.env}"

if [ ! -f "$ENV_FILE" ]; then
    echo "Error: Env file not found at $ENV_FILE"
    echo "Create it (or copy .deploy.env.example) and re-run."
    exit 1
fi

# shellcheck disable=SC1090
source "$ENV_FILE"

: "${RESOURCE_GROUP:?Set RESOURCE_GROUP in $ENV_FILE}"
: "${WEBAPP_NAME:?Set WEBAPP_NAME in $ENV_FILE}"
: "${WEBAPP_HOST:?Set WEBAPP_HOST in $ENV_FILE}"

echo "=== Setting Environment Variables for $WEBAPP_NAME ==="

az webapp config appsettings set \
    --resource-group "$RESOURCE_GROUP" \
    --name "$WEBAPP_NAME" \
    --settings \
    ENVIRONMENT="${ENVIRONMENT}" \
    FRONTEND_HOST="${WEBAPP_HOST}" \
    BACKEND_CORS_ORIGINS="${BACKEND_CORS_ORIGINS}" \
    \
    POSTGRES_SERVER="${POSTGRES_SERVER}" \
    POSTGRES_PORT="${POSTGRES_PORT}" \
    POSTGRES_USER="${POSTGRES_USER}" \
    POSTGRES_PASSWORD="${POSTGRES_PASSWORD}" \
    POSTGRES_DB="${POSTGRES_DB}" \
    \
    AZURE_API_KEY_1="${AZURE_API_KEY_1}" \
    AZURE_API_BASE_1="${AZURE_API_BASE_1}" \
    AZURE_API_VERSION_1="${AZURE_API_VERSION_1}" \
    \
    AZURE_API_KEY_2="${AZURE_API_KEY_2}" \
    AZURE_API_BASE_2="${AZURE_API_BASE_2}" \
    AZURE_API_VERSION_2="${AZURE_API_VERSION_2}" \
    \
    AZURE_API_KEY_3="${AZURE_API_KEY_3}" \
    AZURE_API_BASE_3="${AZURE_API_BASE_3}" \
    AZURE_API_VERSION_3="${AZURE_API_VERSION_3}" \
    \
    AZURE_MODEL_RESOURCE_MAP="${AZURE_MODEL_RESOURCE_MAP}" \
    \
    MODELS="${MODELS}" \
    \
    OPENAI_API_KEY="${OPENAI_API_KEY}" \
    OPENROUTER_API_KEY="${OPENROUTER_API_KEY}" \
    \
    WORDPRESS_MIRROR_URL="${WORDPRESS_MIRROR_URL}" \
    WORDPRESS_WEBSITE_URL="${WORDPRESS_WEBSITE_URL}" \
    \
    CHATBOT_MODEL="${CHATBOT_MODEL}" \
    CHATBOT_MODEL_TEMPERATURE="${CHATBOT_MODEL_TEMPERATURE}" \
    EXTRACTOR_MODEL="${EXTRACTOR_MODEL}" \
    EXTRACTOR_MODEL_TEMPERATURE="${EXTRACTOR_MODEL_TEMPERATURE}" \
    GUARDRAIL_MODEL="${GUARDRAIL_MODEL}" \
    GUARDRAIL_MODEL_TEMPERATURE="${GUARDRAIL_MODEL_TEMPERATURE}" \
    SEARCH_AGENT_MODEL="${SEARCH_AGENT_MODEL}" \
    SEARCH_AGENT_MODEL_TEMPERATURE="${SEARCH_AGENT_MODEL_TEMPERATURE}" \
    EVALUATION_MODEL="${EVALUATION_MODEL}" \
    EVALUATION_MODEL_TEMPERATURE="${EVALUATION_MODEL_TEMPERATURE}" \
    SUMMARIZER_MODEL="${SUMMARIZER_MODEL}" \
    \
    ENABLE_GUARDRAILS="${ENABLE_GUARDRAILS}" \
    MAX_GUARDRAILS_RETRIES="${MAX_GUARDRAILS_RETRIES}" \
    \
    LLM_REQUEST_TIMEOUT="${LLM_REQUEST_TIMEOUT}" \
    \
    USER_REGISTRATION_TOKEN="${USER_REGISTRATION_TOKEN}" \
    ADMIN_REGISTRATION_TOKEN="${ADMIN_REGISTRATION_TOKEN}" \
    REGISTRATION_TOKEN="${REGISTRATION_TOKEN}" \
    JWT_SECRET_KEY="${JWT_SECRET_KEY}" \
    JWT_ALGORITHM="${JWT_ALGORITHM}" \
    JWT_EXPIRE_MINUTES="${JWT_EXPIRE_MINUTES}" \
    \
    SCHEDULER="${SCHEDULER}" \
    \
    SCM_DO_BUILD_DURING_DEPLOYMENT="${SCM_DO_BUILD_DURING_DEPLOYMENT}" \
    WEBSITE_HTTPLOGGING_RETENTION_DAYS="${WEBSITE_HTTPLOGGING_RETENTION_DAYS}" \
    --output none

echo "=== Environment variables set ==="
