"""auto_migration

Revision ID: 2cf06bb14675
Revises:
Create Date: 2026-01-13 19:19:43.127727

"""

from collections.abc import Sequence
from typing import Any, cast

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision: str = "2cf06bb14675"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "chat_completion_trace",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=True),
        sa.Column("max_tokens", sa.Integer(), nullable=True),
        sa.Column("messages", sa.String(), nullable=False),
        sa.Column("completion", sa.String(), nullable=True),
        sa.Column("completion_model", sa.String(), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("guardrails", sa.String(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("duration", sa.Float(), nullable=False),
        sa.Column("response_format_json_schema", sa.String(), nullable=True),
        sa.Column("tools", sa.String(), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "document",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("wp_page", "wp_post", "wp_program", name="document_type_enum"),
            nullable=False,
        ),
        sa.Column("id_", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("markdown_content", sa.String(), nullable=False),
        cast(sa.Column[Any], sa.Column("title_embedding", Vector(dim=1536), nullable=False)),
        sa.Column("source_created_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("source_updated_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_document_title_embedding",
        "document",
        ["title_embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"title_embedding": "vector_l2_ops"},
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("role", sa.Enum("user", "admin", "dev", name="userrole"), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "chatbot_version",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_deployed", sa.Boolean(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chatbot_version_created_by_id"), "chatbot_version", ["created_by_id"], unique=False
    )
    op.create_index(
        op.f("ix_chatbot_version_is_deployed"), "chatbot_version", ["is_deployed"], unique=False
    )
    op.create_table(
        "document_content_chunk",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        cast(sa.Column[Any], sa.Column("content_embedding", Vector(dim=1536), nullable=False)),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["document.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_document_content_chunk_content_embedding",
        "document_content_chunk",
        ["content_embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"content_embedding": "vector_l2_ops"},
    )
    op.create_index(
        op.f("ix_document_content_chunk_document_id"),
        "document_content_chunk",
        ["document_id"],
        unique=False,
    )
    op.create_table(
        "template_conversation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("user", sa.Boolean(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_template_conversation_is_public"),
        "template_conversation",
        ["is_public"],
        unique=False,
    )
    op.create_index(
        op.f("ix_template_conversation_user_id"), "template_conversation", ["user_id"], unique=False
    )
    op.create_table(
        "conversation_sync",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("zip", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=True),
        sa.Column("last_message_id", sa.String(), nullable=False),
        sa.Column("transcript", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("environment", sa.String(), nullable=True),
        sa.Column("program", sa.String(), nullable=True),
        sa.Column("online", sa.Boolean(), nullable=True),
        sa.Column("military_affiliated", sa.Boolean(), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["template_conversation.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversation_sync_conversation_id"),
        "conversation_sync",
        ["conversation_id"],
        unique=False,
    )
    op.create_table(
        "prompt_template",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("chatbot_version_id", sa.Uuid(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["chatbot_version_id"], ["chatbot_version.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_prompt_template_version_filename",
        "prompt_template",
        ["chatbot_version_id", "filename"],
        unique=True,
    )
    op.create_index(
        op.f("ix_prompt_template_chatbot_version_id"),
        "prompt_template",
        ["chatbot_version_id"],
        unique=False,
    )
    op.create_table(
        "template_conversation_feedback",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        cast(
            sa.Column[Any],
            sa.Column(
                "rating",
                postgresql.ENUM("THUMBS_UP", "THUMBS_DOWN", name="rating_enum"),
                nullable=False,
            ),
        ),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["template_conversation.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_template_conversation_feedback_conversation_id"),
        "template_conversation_feedback",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_template_conversation_feedback_user_id"),
        "template_conversation_feedback",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "template_message",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("guardrails_blocked", sa.Boolean(), nullable=False),
        sa.Column("active_child_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["active_child_id"], ["template_message.id"]),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["template_conversation.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["template_message.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_template_message_active_child_id"),
        "template_message",
        ["active_child_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_template_message_conversation_id"),
        "template_message",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_template_message_parent_id"), "template_message", ["parent_id"], unique=False
    )
    op.create_table(
        "template_assistant_message_metadata",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("tool_calls", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("guardrails", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("system_prompt_rendered", sa.String(), nullable=False),
        sa.Column("conversation_turn", sa.Integer(), nullable=False),
        sa.Column("total_time", sa.Float(), nullable=True),
        sa.Column("chatbot_chat_completion_trace_id", sa.Uuid(), nullable=True),
        sa.Column("search_model_settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "guardrail_model_settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("search_time", sa.Float(), nullable=True),
        sa.Column("guardrail_time", sa.Float(), nullable=True),
        sa.Column("chatbot_times", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("guardrail_times", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["chatbot_chat_completion_trace_id"], ["chat_completion_trace.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["message_id"], ["template_message.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_template_assistant_message_metadata_chatbot_chat_completion_trace_id"),
        "template_assistant_message_metadata",
        ["chatbot_chat_completion_trace_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_template_assistant_message_metadata_message_id"),
        "template_assistant_message_metadata",
        ["message_id"],
        unique=True,
    )
    op.create_table(
        "template_message_feedback",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        cast(
            sa.Column[Any],
            sa.Column(
                "rating",
                postgresql.ENUM("THUMBS_UP", "THUMBS_DOWN", name="rating_enum"),
                nullable=False,
            ),
        ),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["template_message.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_template_message_feedback_message_id"),
        "template_message_feedback",
        ["message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_template_message_feedback_user_id"),
        "template_message_feedback",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_template_message_feedback_user_id"), table_name="template_message_feedback"
    )
    op.drop_index(
        op.f("ix_template_message_feedback_message_id"), table_name="template_message_feedback"
    )
    op.drop_table("template_message_feedback")
    op.drop_index(
        op.f("ix_template_assistant_message_metadata_message_id"),
        table_name="template_assistant_message_metadata",
    )
    op.drop_index(
        op.f("ix_template_assistant_message_metadata_chatbot_chat_completion_trace_id"),
        table_name="template_assistant_message_metadata",
    )
    op.drop_table("template_assistant_message_metadata")
    op.drop_index(op.f("ix_template_message_parent_id"), table_name="template_message")
    op.drop_index(op.f("ix_template_message_conversation_id"), table_name="template_message")
    op.drop_index(op.f("ix_template_message_active_child_id"), table_name="template_message")
    op.drop_table("template_message")
    op.drop_index(
        op.f("ix_template_conversation_feedback_user_id"),
        table_name="template_conversation_feedback",
    )
    op.drop_index(
        op.f("ix_template_conversation_feedback_conversation_id"),
        table_name="template_conversation_feedback",
    )
    op.drop_table("template_conversation_feedback")
    op.drop_index(op.f("ix_prompt_template_chatbot_version_id"), table_name="prompt_template")
    op.drop_index("idx_prompt_template_version_filename", table_name="prompt_template")
    op.drop_table("prompt_template")
    op.drop_index(op.f("ix_conversation_sync_conversation_id"), table_name="conversation_sync")
    op.drop_table("conversation_sync")
    op.drop_index(op.f("ix_template_conversation_user_id"), table_name="template_conversation")
    op.drop_index(op.f("ix_template_conversation_is_public"), table_name="template_conversation")
    op.drop_table("template_conversation")
    op.drop_index(
        op.f("ix_document_content_chunk_document_id"), table_name="document_content_chunk"
    )
    op.drop_index(
        "idx_document_content_chunk_content_embedding",
        table_name="document_content_chunk",
        postgresql_using="hnsw",
        postgresql_ops={"content_embedding": "vector_l2_ops"},
    )
    op.drop_table("document_content_chunk")
    op.drop_index(op.f("ix_chatbot_version_is_deployed"), table_name="chatbot_version")
    op.drop_index(op.f("ix_chatbot_version_created_by_id"), table_name="chatbot_version")
    op.drop_table("chatbot_version")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(
        "idx_document_title_embedding",
        table_name="document",
        postgresql_using="hnsw",
        postgresql_ops={"title_embedding": "vector_l2_ops"},
    )
    op.drop_table("document")
    op.drop_table("chat_completion_trace")
    # ### end Alembic commands ###
